const INCREMENT_NUMBER = 'INCREMENT_NUMBER'
const DECREMENT_NUMBER = 'DECREMENT_NUMBER'
const TRIGGER_INCREMENT = 'TRIGGER_INCREMENT'
const DOUBLE_NUMBER = 'DOUBLE_NUMBER'
const ADD_THREE = 'ADD_THREE'
const REQUEST_DATA = 'REQUEST_DATA'
const SET_NUMBER = 'SET_NUMBER'
const SET_DATA = 'SET_DATA'
const ADD_TO_NUMBER = 'ADD_TO_NUMBER'
const NUMBER = 'NUMBER'
const DATA = 'DATA'
const CHANGE_OBJECT = 'CHANGE_OBJECT'
const CHECK_PERFORMANCE = 'CHECK_PERFORMANCE'
const COMBINED = 'COMBINED'
const CHECK_GETTERS = 'CHECK_GETTERS'
const START_INTERVAL = 'START_INTERVAL'
const WRITE_INTERVAL = 'WRITE_INTERVAL'
const INTERVAL_OFF = 'INTERVAL_OFF'
const PROXY_INCREMENT = 'PROXY_INCREMENT'

module.exports = {
  INTERVAL_OFF,
  START_INTERVAL,
  TRIGGER_INCREMENT,
  WRITE_INTERVAL,
  CHECK_GETTERS,
  COMBINED,
  CHANGE_OBJECT,
  CHECK_PERFORMANCE,
  INCREMENT_NUMBER,
  DECREMENT_NUMBER,
  DOUBLE_NUMBER,
  ADD_TO_NUMBER,
  ADD_THREE,
  REQUEST_DATA,
  SET_NUMBER,
  SET_DATA,
  NUMBER,
  DATA,
  PROXY_INCREMENT
}
